version: '2'
services:
  altenvehiclemonitorserver-app:
    image: altenvehiclemonitorserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://altenvehiclemonitorserver-postgresql:5432/altenvehiclemonitorserver
      - APPLICATION_MQTTBORKERCONFIG_URL=tcp://altenvehiclemonitorserver-rabbit:1883
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  altenvehiclemonitorserver-postgresql:
    extends:
      file: postgresql.yml
      service: altenvehiclemonitorserver-postgresql
  altenvehiclemonitorserver-rabbit:
    extends:
      file: rabbitmq.yml
      service: altenvehiclemonitorserver-rabbit
