version: '2'
services:
  altenvehiclemonitorserver-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/altenvehiclemonitorserver/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=altenvehiclemonitorserver
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
