version: '2'
services:
  altenvehiclemonitorserver-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/altenvehiclemonitorserver/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=704351293
      - POSTGRES_DB=altenvehiclemonitorserver
    ports:
      - 5432:5432
